storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage
   
dataset:
 value: mnist
 version: '1.0.0'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Mnist dataset configuration"
   kind: dataset

storage_b:
 value: true
 wizard:
   name: "Storage boolean"
   kind: boolean

select_option:
 value: ""
 wizard:
   name: "Select oprion"
   kind: "select"
   options:
    - "1.0.0"
    - "1.0.1"
   dynamic: true

tensorflow_version:
  value: "1.5.0"
  wizard:
    name: "Tensorflow version"
    kind: select
    options:
    - "1.2.0"
    - "1.3.0"
    - "1.4.0"
    - "1.5.0"

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

serving_port: 9000

tf_serving: false
